### ISSUE TITLE
Feature: Give characters foot step sounds

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/community-rpg#14]
Many games play different foot step sounds depending on which surface a character is walking on. 

For example, if the player was walking on grass, each foot step event would play a random sound from a pool of grass walking sounds. If the player moved to a stone surface, the game would play the sound of boots stepping on stone instead.

To get started on this, we could simplify the tile types into the following categories:
| Sound set | Example tiles in map |
|---------------|------------------------------|
| Grass | Light grass, Dark grass |
| Stone | Cobblestone path, Dungeon floor |
| Dirt     | Dirt path, Garden, Graveyard |
| Wood | House interior, Bridges |
| Sand | Beaches |

We can pull sounds from [Kenney's impact sounds set](https://kenney.nl/assets/impact-sounds). It is licensed under a [CC0 1.0 Universal Public Domain Dedication](https://creativecommons.org/publicdomain/zero/1.0/), which means there are no licensing restrictions at all. However, It would still be polite to cite the source.

This ticket should synchronize with the same animation speed used to fix #5. The sound files should be placed in a directory under `resources`.

**Comment by Cleptomania** [comment]
Added in #21 though we could do with a more full featured system for this in the future maybe, but that should probably a separate issue.
