### ISSUE TITLE
Bug: Sprite movement animation speeds are too high

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/community-rpg#5]
**Describe the bug**
Animations for moving character sprites are too fast, resulting in jitter or flicker instead of a convincing walking movement.

**To Reproduce**
1. Launch game
2. Observe the cat moving, or move the player character with WASD/arrows

**Expected behavior**
A reasonable pace for animations that looks like walking

**Screenshots**
Wayland is making it hard to capture video, so I apologize for not including a webm of the problem.

**Desktop (please complete the following information):**
 - OS: Linux, Debian 11
 - GPU: UHD Graphics 620
 - DE: Gnome 3.38.5 on Wayland

**Comment by Cleptomania** [comment]
The platformer tutorial for Arcade has an example of a way to fix this.

https://api.arcade.academy/en/latest/examples/platform_tutorial/step_14.html

It doesn't apply 1:1 here, but basically we just need to keep track of a value for if you we should update the animation or not, and if we should then do it and reset the value, and if not then just increment that value.

**Comment by Revan20911** [comment]
Hello, I would like to take a look at this if that is ok?

**Comment by Cleptomania** [comment]
This was fixed in #17
